const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const A='UC'+'a'.repeat(22),B='UC'+'b'.repeat(22),V='a'.repeat(11),W='b'.repeat(11);
(async()=>{
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'ledger-features-'));let context;const errors=[];
 try{
  const extension=path.join(__dirname,'dist/chrome');context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,viewport:{width:1440,height:1000},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
  context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).host;
  await context.route('https://www.youtube.com/**',route=>{
   const u=new URL(route.request().url());if(!['document','fetch','xhr'].includes(route.request().resourceType()))return route.fulfill({status:204,body:''});
   const c=u.pathname.includes(B)?B:A;return route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta property="og:title" content="${c===A?'Alpha':'Beta'}"><link rel="canonical" href="https://www.youtube.com/channel/${c}"><style>body{font:14px Arial;background:#171717;color:white}ytd-guide-renderer{display:block;width:230px;float:left}ytd-page-manager{display:block;margin-left:240px}ytd-guide-section-renderer,ytd-guide-entry-renderer{display:block}button,a{color:inherit}@media(max-width:700px){ytd-guide-renderer{display:none}ytd-page-manager{margin-left:0}}</style></head><body><ytd-masthead><div id="center"><yt-searchbox><input></yt-searchbox></div></ytd-masthead><ytd-guide-renderer><div id="sections"><ytd-guide-section-renderer><a href="/feed/subscriptions">Subscriptions</a></ytd-guide-section-renderer><ytd-guide-section-renderer><ytd-guide-entry-renderer><a href="/channel/${A}">Alpha</a></ytd-guide-entry-renderer></ytd-guide-section-renderer></div></ytd-guide-renderer><ytd-page-manager><ytd-browse page-subtype="${u.pathname==='/'?'home':'subscriptions'}"><a id="recommended" href="/watch?v=${V}" target="_blank">Recommended video</a><ytd-channel-renderer><a href="/channel/${B}">Beta</a></ytd-channel-renderer><video></video><button class="ytp-autonav-toggle-button" aria-checked="true">Autoplay</button><a class="ytp-next-button" href="/watch?v=${W}">Next</a></ytd-browse></ytd-page-manager><script>window.leakedMenuKeys=[];window.addEventListener('keydown',event=>{if([' ','ArrowDown','ArrowUp','Escape'].includes(event.key)){window.leakedMenuKeys.push(event.key);event.preventDefault();}},true);</script></body></html>`});
  });
  await context.route('https://i.ytimg.com/**',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="480" height="270"><rect width="480" height="270" fill="#2d493b"/><circle cx="240" cy="135" r="70" fill="#415d4d"/></svg>'}));
  const day=await worker.evaluate(()=>Ledger.dayKey(Date.now()));
  await worker.evaluate(({A,B,V,W,day})=>{
   const now=Date.now(),rows=[];for(const [name,source,seconds] of [['g',{kind:'group',groupId:'podcasts',groupName:'Podcasts'},3],['r',{kind:'recommendations'},4]])Ledger.add(rows,{id:name,videoId:V,title:'Episode one',channel:'Alpha',url:'https://www.youtube.com/watch?v='+V,start:now-seconds*1000,end:now,state:'foreground',source});
   return chrome.storage.local.set({settings:Ledger.settings({hideRecommendations:false}),['day:'+day]:rows,['goals:'+day]:'Listen thoughtfully','channelGroups:v1':{version:1,groups:[{id:'podcasts',name:'Podcasts',channelIds:[A],createdAt:now,updatedAt:now},{id:'music',name:'Music',channelIds:[],createdAt:now,updatedAt:now}],channels:{[A]:{id:A,name:'Alpha',url:'https://www.youtube.com/channel/'+A}}},'channelUploads:v1':{version:1,channels:{[A]:{fetchedAt:now,attemptedAt:now,error:'',entries:[{videoId:V,channelId:A,channel:'Alpha',title:'Episode one',publishedAt:now-2*3600000},{videoId:W,channelId:A,channel:'Alpha',title:'Episode two',publishedAt:now-2*86400000}]}}}});
  },{A,B,V,W,day});
  const dashboard=await context.newPage();await dashboard.goto(`chrome-extension://${id}/dashboard.html#history`);
  await dashboard.locator('#source-totals').filter({hasText:'Group: Podcasts: 3s'}).waitFor();assert.match(await dashboard.locator('#rows').innerText(),/Recommendations · 4s/);
  await dashboard.locator('#source-filter').selectOption('group:podcasts');await dashboard.locator('#rows .source-badges').filter({hasText:'Group: Podcasts · 3s'}).waitFor();assert.doesNotMatch(await dashboard.locator('#rows').innerText(),/Recommendations/);assert.match(await dashboard.locator('#review-rows').innerText(),/Recommendations · 4s/);
  await dashboard.evaluate(()=>document.activeElement.blur());
  const page=await context.newPage();await page.goto('https://www.youtube.com/feed/subscriptions#ledger-group=podcasts');const feed=page.locator('#ledger-group-feed'),sidebar=page.locator('#ledger-groups-sidebar');await feed.locator('article').nth(1).waitFor();
  assert.match(await feed.locator('time').first().innerText(),/2 hours ago/);assert.match(await feed.locator('time').nth(1).innerText(),/2 days ago/);assert.ok(await feed.locator('time').first().getAttribute('title'));
  assert.equal(await feed.locator('article select').count(),0,'Cards have no persistent dropdown');
  const firstOptions=feed.getByRole('button',{name:'More options for Episode one',exact:true}),secondOptions=feed.getByRole('button',{name:'More options for Episode two',exact:true}),menu=feed.getByRole('menu',{name:'Watch options'});
  await secondOptions.click();assert.equal(await menu.getByRole('menuitem').count(),3);assert.equal(await menu.getByRole('menuitem',{name:'Use recorded playback'}).count(),0,'Automatic state needs no reset action');
  await firstOptions.click();assert.equal(await menu.count(),1);assert.equal(await secondOptions.getAttribute('aria-expanded'),'false');assert.equal(await menu.getByRole('menuitem').count(),4);
  await page.keyboard.press('ArrowDown');assert.equal(await menu.getByRole('menuitem',{name:'Mark unwatched',exact:true}).evaluate(node=>node.getRootNode().activeElement===node),true);
  await page.keyboard.press('Home');assert.equal(await menu.getByRole('menuitem',{name:'Mark watched',exact:true}).evaluate(node=>node.getRootNode().activeElement===node),true);
  // A storage refresh must not detach the focused menu or its card.
  await menu.evaluate(node=>window.openWatchMenu=node);
  await worker.evaluate(V=>chrome.storage.local.set({'videoProgress:v1':{version:1,videos:{[V]:{observed:true,segments:[]}}}}),V);
  await page.waitForTimeout(250);assert.equal(await menu.evaluate(node=>node===window.openWatchMenu),true);
  await page.keyboard.press('Enter');await menu.waitFor({state:'detached'});await feed.locator('.watch-badge[title="Marked manually"]').filter({hasText:'Watched'}).waitFor();
  assert.equal(await firstOptions.evaluate(node=>node.getRootNode().activeElement===node),true,'Saving returns focus to the menu trigger');
  await firstOptions.press('ArrowDown');await menu.getByRole('menuitem',{name:'Use recorded playback',exact:true}).waitFor();
  await page.keyboard.press('Escape');await menu.waitFor({state:'detached'});assert.equal(await firstOptions.evaluate(node=>node.getRootNode().activeElement===node),true);
  await firstOptions.click();await menu.getByRole('menuitem',{name:'Use recorded playback',exact:true}).click();await menu.waitFor({state:'detached'});await feed.locator('article').first().getByText('Started',{exact:true}).waitFor();
  await firstOptions.click();assert.equal(await menu.getByRole('menuitem',{name:'Use recorded playback'}).count(),0);await feed.getByRole('heading',{name:'Podcasts',exact:true}).click();await menu.waitFor({state:'detached'});
  await page.setViewportSize({width:390,height:850});await firstOptions.click();const box=await menu.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390&&box.y>=0&&box.y+box.height<=850,'Menu fits a narrow viewport');
  await menu.screenshot({path:path.join(__dirname,'group-watch-menu-preview.png')});await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});
  // Filtering a changed card out should leave usable keyboard focus.
  await feed.getByRole('button',{name:'Unwatched',exact:true}).click();await firstOptions.click();await menu.getByRole('menuitem',{name:'Mark watched',exact:true}).click();await firstOptions.waitFor({state:'detached'});
  assert.equal(await feed.getByRole('button',{name:'Unwatched',exact:true}).evaluate(node=>node.getRootNode().activeElement===node),true);
  await feed.getByRole('button',{name:'All videos',exact:true}).click();await firstOptions.waitFor();
  assert.deepEqual(await page.evaluate(()=>window.leakedMenuKeys),[],'Menu keys never reach YouTube player shortcuts');
  await feed.getByRole('button',{name:'Unwatched',exact:true}).click();await feed.locator('article').filter({hasText:'Episode one'}).waitFor({state:'detached'});assert.equal(await feed.locator('article').count(),1);
  await feed.getByRole('button',{name:'All videos',exact:true}).click();await feed.locator('article').nth(1).waitFor();
  await page.screenshot({path:path.join(__dirname,'groups-features-preview.png')});
  await sidebar.getByRole('button',{name:'Toggle groups'}).click();await sidebar.getByRole('link',{name:'Podcasts',exact:true}).waitFor({state:'detached'});await page.reload();await sidebar.getByRole('button',{name:'Toggle groups'}).waitFor();assert.equal(await sidebar.getByRole('link',{name:'Podcasts',exact:true}).count(),0);await sidebar.getByRole('button',{name:'Toggle groups'}).click();
  await sidebar.getByRole('button',{name:'Options for Podcasts',exact:true}).click();await page.getByRole('menuitem',{name:'Manage group',exact:true}).click();let manager=page.getByRole('dialog',{name:'Manage group'});await manager.getByRole('button',{name:'Move down',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#ledger-groups-sidebar').shadowRoot.querySelector('.nav-item').dataset.groupId==='music');
  await manager.getByRole('textbox',{name:'Group name',exact:true}).fill('Conversations');await manager.getByRole('button',{name:'Rename',exact:true}).click();await sidebar.getByRole('link',{name:'Conversations',exact:true}).waitFor();await manager.getByRole('button',{name:'Close',exact:true}).click();
  await sidebar.getByRole('button',{name:'Add multiple channels',exact:true}).click();const bulk=page.getByRole('dialog',{name:'Add multiple channels'});await bulk.getByRole('checkbox',{name:'Alpha',exact:true}).check();await bulk.getByRole('checkbox',{name:'Beta',exact:true}).check();await bulk.getByRole('checkbox',{name:'Music',exact:true}).check();await bulk.getByRole('checkbox',{name:'Conversations',exact:true}).check();await bulk.screenshot({path:path.join(__dirname,'groups-bulk-preview.png')});await bulk.getByRole('button',{name:'Add selected channels'}).click();await bulk.getByRole('status').filter({hasText:'Added 2 channels to 2 groups.'}).waitFor();await bulk.getByRole('button',{name:'Done',exact:true}).click();
  assert.deepEqual(await worker.evaluate(()=>chrome.storage.local.get('channelGroups:v1').then(d=>d['channelGroups:v1'].groups.map(g=>g.channelIds.length))),[2,2]);
  // Full backup via the real download and file-picker controls.
  await page.close();await dashboard.getByRole('link',{name:'Settings',exact:true}).click();
  const download=dashboard.waitForEvent('download');await dashboard.getByRole('button',{name:'Export profile'}).click();const file=path.join(profile,'backup.json');await(await download).saveAs(file);const backup=JSON.parse(fs.readFileSync(file));assert.equal(backup.format,'youtube-ledger-backup');assert.equal(backup.data['goals:'+day],'Listen thoughtfully');
  backup.data.settings.theme='retrowave';backup.data.settings.reviewPreference='Preserve my restored review prompt.';fs.writeFileSync(file,JSON.stringify(backup));
  await worker.evaluate(()=>chrome.storage.local.set({'channelGroups:v1':{version:1,groups:[],channels:{}}}));await dashboard.locator('#backup-file').setInputFiles(file);await dashboard.locator('#backup-summary').filter({hasText:'2 groups'}).waitFor();
  await dashboard.getByRole('button',{name:'Replace with this profile'}).click();await dashboard.locator('#backup-status').filter({hasText:'Profile imported.'}).waitFor();assert.equal(await worker.evaluate(()=>chrome.storage.local.get('channelGroups:v1').then(d=>d['channelGroups:v1'].groups.length)),2);
  assert.equal(await dashboard.locator('#setting-theme').inputValue(),'retrowave');assert.equal(await dashboard.locator('#setting-reviewPreference').inputValue(),'Preserve my restored review prompt.');
  await dashboard.locator('#setting-showPausedOnly').check();await dashboard.waitForFunction(async()=>(await browser.storage.local.get('settings')).settings.showPausedOnly);
  const restoredSettings=await worker.evaluate(()=>chrome.storage.local.get('settings').then(d=>d.settings));assert.equal(restoredSettings.theme,'retrowave');assert.equal(restoredSettings.reviewPreference,'Preserve my restored review prompt.');assert.equal(restoredSettings.showPausedOnly,true);
  // Observe a supported recommendation link actually opening a new tab.
  const home=await context.newPage();await home.goto('https://www.youtube.com/');await home.locator('#ledger-groups-sidebar').waitFor();
  const pop=context.waitForEvent('page');await home.locator('#recommended').click();const watch=await pop;await watch.waitForLoadState('domcontentloaded');
  async function source(p){const session=await context.newCDPSession(p),worlds=[];session.on('Runtime.executionContextCreated',({context})=>worlds.push(context));await session.send('Runtime.enable');const world=worlds.find(w=>w.name===id||w.origin==='chrome-extension://'+id);if(!world){await session.detach();return null;}const result=await session.send('Runtime.evaluate',{contextId:world.id,expression:'JSON.stringify(PlaybackSource.read(new URL(location.href).searchParams.get("v")))',returnByValue:true});await session.detach();return result.result.value?JSON.parse(result.result.value):null;}
  let observed;for(let i=0;i<20;i++){observed=await source(watch);if(observed?.source.kind==='recommendations')break;await watch.waitForTimeout(100);}assert.equal(observed?.source.kind,'recommendations');assert.match(watch.url(),/ledger-origin=/);
  await watch.evaluate(W=>{document.querySelector('video').dispatchEvent(new Event('ended',{bubbles:true}));history.pushState({},'','/watch?v='+W);document.dispatchEvent(new Event('yt-navigate-finish'));},W);assert.equal((await source(watch)).source.kind,'autoplay');
  await watch.evaluate(V=>{history.pushState({},'','/watch?v='+V);document.dispatchEvent(new Event('yt-navigate-finish'));},V);assert.equal((await source(watch)).source.kind,'unknown');
  assert.deepEqual(errors,[]);console.log('PASS: visible source totals/filtering, relative timestamps, watch state/filter, collapse/reload, sidebar reorder/rename, bulk memberships, backup download/restore, actual new-tab provenance, supported autoplay and Unknown fallback.');
 }finally{await context?.close();fs.rmSync(profile,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1)});
