const {chromium} = require('playwright');
const assert = require('node:assert/strict');
(async()=>{
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  try {
    const page = await browser.newPage({viewport:{width:1280,height:960}});
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.addInitScript(()=>{
      const d=new Date(), day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
      const data=JSON.parse(sessionStorage.getItem('test-data') || 'null') || {['day:'+day]:[{id:'demo',title:'Example session — learning something useful',channel:'Example channel',videoId:'demo',url:'https://www.youtube.com/watch?v=demo',start:Date.now()-1800000,end:Date.now(),label:'Learning',seconds:{foreground:1200,backgroundAudio:300,backgroundSilent:0,paused:300,browsing:0,ad:0}}]};
      data['purposes:'+day]={'video:demo':'Learning'};data['recommendations:'+day]=[{kind:'reveal',at:Date.now(),page:'/'}];
      window.browser={storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,data[k]])),set:async x=>{Object.assign(data,x);sessionStorage.setItem('test-data',JSON.stringify(data));}}},runtime:{sendMessage:async m=>{if(m.type==='groupLabel') data['purposes:'+m.day][m.key]=m.label;}}};
    });
    await page.goto('file://'+__dirname+'/dashboard.html');
    await page.getByText('20m 0s',{exact:true}).first().waitFor();
    await page.getByText(/1 reveals/).waitFor();
    await page.getByRole('combobox').selectOption('Work');
    await page.getByRole('button',{name:'Pause tracking',exact:true}).click();
    await page.getByRole('button',{name:'Resume tracking',exact:true}).waitFor();
    await page.locator('#goals').fill('30 minutes of intentional learning.');
    const downloadPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Export LLM review prompt',exact:true}).click();
    const download=await downloadPromise;
    assert.match(download.suggestedFilename(),/^youtube-review-/);
    await page.getByText('Advanced settings',{exact:true}).click();
    assert.equal(await page.locator('#setting-reviewPreference').inputValue(),'');
    await page.locator('#setting-hideRecommendations').uncheck();
    await page.locator('#setting-shortMinutes').fill('7');
    await page.locator('#setting-theme').selectOption('classic');
    assert.equal(await page.locator('html').getAttribute('data-theme'),'classic');
    await page.getByText('Theme saved. Other changes still need Save settings.',{exact:true}).waitFor();
    assert.equal(await page.evaluate(async()=>(await browser.storage.local.get(['settings'])).settings.theme),'classic');
    // A normal dashboard refresh cannot revert the newly selected theme.
    await page.evaluate(()=>render());
    assert.equal(await page.locator('html').getAttribute('data-theme'),'classic');
    await page.getByRole('button',{name:'Save settings',exact:true}).click();
    await page.getByText('Settings saved.',{exact:true}).waitFor();
    await page.getByText(/≤7 min today/).waitFor();
    assert.equal(await page.locator('html').getAttribute('data-theme'),'classic');
    assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(246, 247, 242)');
    await page.screenshot({path:__dirname+'/classic-preview.png',fullPage:true});
    await page.reload();
    await page.getByText('Advanced settings',{exact:true}).click();
    assert.equal(await page.locator('#setting-hideRecommendations').isChecked(),false);
    assert.equal(await page.locator('#setting-shortMinutes').inputValue(),'7');
    assert.equal(await page.locator('#setting-theme').inputValue(),'classic');
    assert.equal(await page.locator('html').getAttribute('data-theme'),'classic');
    await page.locator('#setting-theme').selectOption('dark-green');
    assert.equal(await page.locator('html').getAttribute('data-theme'),'dark-green');
    await page.getByText('Theme saved. Other changes still need Save settings.',{exact:true}).waitFor();
    assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(16, 23, 20)');
    await page.screenshot({path:__dirname+'/dark-green-preview.png',fullPage:true});
    await page.reload();
    await page.getByText('Advanced settings',{exact:true}).click();
    assert.equal(await page.locator('#setting-theme').inputValue(),'dark-green');
    assert.equal(await page.locator('html').getAttribute('data-theme'),'dark-green');
    await page.getByRole('button',{name:'Restore defaults',exact:true}).click();
    await page.getByText('Defaults restored.',{exact:true}).waitFor();
    assert.equal(await page.locator('#setting-hideRecommendations').isChecked(),true);
    assert.deepEqual(errors,[]);
    await page.screenshot({path:__dirname+'/dashboard-preview.png',fullPage:true});
    await page.setViewportSize({width:600,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    console.log('Dashboard checks passed: render, label, pause, goals, export, narrow layout; no JavaScript errors. Screenshot uses synthetic data.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
