"""Rebuild the locally bundled GIF codec from pinned, integrity-checked packages."""
import base64, hashlib, io, json, posixpath, re, tarfile, urllib.request
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
PACKAGES={
 'gifenc':('1.0.3','xdr6AdrfGBcfzncONUOlXMBuc5wJDtOueE3c5rdG0oNgtINLD+f2iFZltrBRZYzACRbKr+mSVU/x98zv2u3jmw=='),
 'gifuct-js':('2.1.2','rI2asw77u0mGgwhV3qA+OEgYqaDn5UNqgs+Bx0FGwSpuqfYn+Ir6RQY5ENNQ8SbIiG/m5gVa7CD5RriO4f4Lsg=='),
 'js-binary-schema-parser':('2.0.3','xezGJmOb4lk/M1ZZLTR/jaBHQ4gG/lqQnJqdIv4721DMggsa1bDVlHXNeHYogaIEHD9vCRv0fcL4hMA+Coarkg==')}
files={};licenses=[]
for name,(version,integrity) in PACKAGES.items():
 raw=urllib.request.urlopen(f'https://registry.npmjs.org/{name}/-/{name}-{version}.tgz').read()
 assert base64.b64encode(hashlib.sha512(raw).digest()).decode()==integrity
 with tarfile.open(fileobj=io.BytesIO(raw),mode='r:gz') as archive:
  for member in archive.getmembers():
   if not member.isfile():continue
   path=member.name.removeprefix('package/')
   if path.endswith('.js'):files[name+'/'+path]=archive.extractfile(member).read().decode()
   if path.lower() in ['license','license.txt','license.md']:licenses.append(name+' '+version+'\n'+archive.extractfile(member).read().decode())
entries={'gifenc':'gifenc/dist/gifenc.js','gifuct-js':'gifuct-js/lib/index.js','js-binary-schema-parser':'js-binary-schema-parser/lib/index.js'}
modules={}
def include(name):
 if name in modules:return
 modules[name]=''
 def dependency(match):
  request=match[1]
  target=posixpath.normpath(posixpath.join(posixpath.dirname(name),request)) if request.startswith('.') else entries.get(request,request)
  target=next((p for p in [target,target+'.js',target+'/index.js'] if p in files),None)
  if not target:raise ValueError(request)
  include(target)
  return 'require('+json.dumps(target)+')'
 modules[name]=re.sub(r'require\([\'"]([^\'"]+)[\'"]\)',dependency,files[name])
include(entries['gifenc']);include(entries['gifuct-js'])
output='/* Generated by scripts/build-gif-codec.py. See THIRD-PARTY-LICENSES.txt. No runtime downloads. */\nglobalThis.GifCodec=(()=>{\nconst modules={\n'
output+=',\n'.join(json.dumps(k)+':function(module,exports,require){\n'+v+'\n}' for k,v in modules.items())
output+='\n},cache={};function require(id){if(cache[id])return cache[id].exports;const module=cache[id]={exports:{}};modules[id](module,module.exports,require);return module.exports;}\nreturn {...require("gifenc/dist/gifenc.js"),...require("gifuct-js/lib/index.js")};})();\n'
(ROOT/'gif-codec.js').write_text(output)
(ROOT/'THIRD-PARTY-LICENSES.txt').write_text('\n\n'.join(licenses)+'\n')
